version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - ${MINIO_S3_API}:9000
      - ${MINIO_WEB_CONSOLE}:9001
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - ./data/minio:/data
  
  mc:
    image: minio/mc:latest
    container_name: mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 minio minio123 &&
      mc mb local/mybucket || true &&
      tail -f /dev/null
      "

  python-client:
    build: ./python-client   # folder where your Dockerfile is
    container_name: python-client
    depends_on:
      - minio
    volumes:
      - ./code:/app
    working_dir: /app
    command: ["python3"]
